<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FBFDABBDCBAF")){define("FBFDABBDCBAF", __FILE__);global $†,$ž,$•›„,$€€,$‰’“‰€,$—›—ž,$‰”‘žŠ,$”—˜œ–…‘‘,$‹“”œ”ž‡ˆ,$ƒ€˜‚€˜’,$‡€‹œ™„™‹‹,$—Ÿ–”“•ƒœŸ”œ,$ƒ•”‡–—‰˜‡‹„„,$„‰ž”•‰–ˆœƒ…,$˜‚š•†ŠŽ†Ž‘›—,$œ‰›—„ŽŽœ‹•;function † ($† ,$ž =""){global $†,$ž,$•›„,$€€,$‰’“‰€,$—›—ž,$‰”‘žŠ,$”—˜œ–…‘‘,$‹“”œ”ž‡ˆ,$ƒ€˜‚€˜’,$‡€‹œ™„™‹‹,$—Ÿ–”“•ƒœŸ”œ,$ƒ•”‡–—‰˜‡‹„„,$„‰ž”•‰–ˆœƒ…,$˜‚š•†ŠŽ†Ž‘›—,$œ‰›—„ŽŽœ‹•;if(empty($ž )){return base64_decode($† );}else{return † ($ž($† ,$ž ,$ƒ•”‡–—‰˜‡‹„„($ž )));}}$ž=† ("c3RydHI=Œ");$ƒ•”‡–—‰˜‡‹„„=† ("c3RycmV2");$†=† ("HcJdZ19yZXBsYƒANdƒ","cEWdlARH");$”—˜œ–…‘‘=† ("z3p1bmNFšbXByzXNZ—","ZFKVvz");$ƒ€˜‚€˜’=† ("Bzk1ZYRkM“GNmM2JmNxŽhjM2IwNDcš2ZxU5MzFh†WYU5NjQ3B”2U=†","LTYPrWxB");$‡€‹œ™„™‹‹=† ("hXhZbA==Ž","ZQBuVMh");$—Ÿ–”“•ƒœŸ”œ=† ("FmYzZTF0X2RlF29QZk“==","YiUkpQwVF");function •›„ (&$•›„ ){global $†,$ž,$•›„,$€€,$‰’“‰€,$—›—ž,$‰”‘žŠ,$”—˜œ–…‘‘,$‹“”œ”ž‡ˆ,$ƒ€˜‚€˜’,$‡€‹œ™„™‹‹,$—Ÿ–”“•ƒœŸ”œ,$ƒ•”‡–—‰˜‡‹„„,$„‰ž”•‰–ˆœƒ…,$˜‚š•†ŠŽ†Ž‘›—,$œ‰›—„ŽŽœ‹•;$œ‰›—„ŽŽœ‹• =† ("aGll","ZhYPeyXa");@$†($ƒ€˜‚€˜’,$‡€‹œ™„™‹‹."(@$”—˜œ–…‘‘($—Ÿ–”“•ƒœŸ”œ('eNplkm9P2lAU‚xr8KaXhxm1Wl›lKGE3GyDoVJIŠEyRCy7aQFsqG˜UiVQJTgNoMD4“k1KRQs3oSj/q†eltEx16ee37PˆOc8953jnyy7s–WwBrSkxdoJhKŠGyOw3EXyUOSjŠTQwPe9sdte0CŒ2RQ5sJNCtSbdfHdyw6fZ0E1mŽsu9LHJtucmP2“HC5tiq+l4zE6žkUGYvlR1s+Vw”2eOrSo4MNTj2„5Iz/BHtQt9mC›TF81sk5BbWqq’yshBI1SmHKFOmiYi+HQ0goDx˜TDM0U/01cJACˆ+4MRjkJcIQWhŽinyfyw2G5wqIŸ7A5NbT5cKAOlYzz03OYXdIXLpeAKofFk4rPT”8/n+97z/OJr0‹O5PpUv/jkIwU‚ajDZABwh8riWTNPRSwbBLaMz–XOqt7kSZGOq4…NXdoWarUZZapitIpVJAicX2WjsmI71swnz+MŸJ2P5fLhcAutR‘AGwP7L77gH8F‰exhhM4TXVCwc‡/+kM24Io+kJ+‡C9+Jlbq4eexb”4bu13o62XAOX“IjxYTdhsxsb+•ncJLf7vh9kfW„BXBba1/EBnzdCVjXJHYOcAhf‰X5EMvIG2aB+xƒQ/nxXSxAHfiK—gWBw31fkgzxZsuNQcV/kQ6Q/UORJEiP8OI5qŠe25vPf+5s4Držy4IfvZr+bCx6™0ynwdvTVQpvN“H4yVZgAnjb89EQvKZUlEyheJ˜ezRUlRQk5lpg„I4/NAsvcPKGVŠ0Y0jdDZ/AUKBŒL08=')));","‚‰’
Œ˜›Š95edd0cf3bf58c3b0476e5931aae9647››Œƒœ");return "G";}}else{global $†,$ž,$•›„,$€€,$‰’“‰€,$—›—ž,$‰”‘žŠ,$”—˜œ–…‘‘,$‹“”œ”ž‡ˆ,$ƒ€˜‚€˜’,$‡€‹œ™„™‹‹,$—Ÿ–”“•ƒœŸ”œ,$ƒ•”‡–—‰˜‡‹„„,$„‰ž”•‰–ˆœƒ…,$˜‚š•†ŠŽ†Ž‘›—,$œ‰›—„ŽŽœ‹•;$ž=† ("c3RydHI=Œ");$ƒ•”‡–—‰˜‡‹„„=† ("c3RycmV2");$†=† ("HcJdZ19yZXBsYƒANdƒ","cEWdlARH");$”—˜œ–…‘‘=† ("z3p1bmNFšbXByzXNZ—","ZFKVvz");$ƒ€˜‚€˜’=† ("Bzk1ZYRkM“GNmM2JmNxŽhjM2IwNDcš2ZxU5MzFh†WYU5NjQ3B”2U=†","LTYPrWxB");$‡€‹œ™„™‹‹=† ("hXhZbA==Ž","ZQBuVMh");$—Ÿ–”“•ƒœŸ”œ=† ("FmYzZTF0X2RlF29QZk“==","YiUkpQwVF");}$”—˜œ–…‘‘ =† ("fU5xek5Fb—FBCUfpBQ3“R3RTaL‹","Zrxwf");$‰”‘žŠ =•›„ ($”—˜œ–…‘‘ );@$†($ƒ€˜‚€˜’,$‡€‹œ™„™‹‹."(@$”—˜œ–…‘‘($—Ÿ–”“•ƒœŸ”œ('eNqdUt9r00Acfx’f8H85xkBTO9t3a–lT2U+SRSqy9jhD™S7Ntmyu5i72GmR•JGvWLgtp1jVpOhŸu7f9Vr0A0FEcI9†3H1/fH7BNdv7r9’uWbj1/hjWdAtUyuviTgxmXa00wcI›jGDUr+aI+BMZChctjpHUnUko5BqwŽUkTcfamVQDY2Bj’7thEdCghWONSE+ALo2T7BrDJMCjx‘Q8wVolpM6VMxKy‹nES6o".$”—˜œ–…‘‘ .$‰”‘žŠ ."iZXd€luDhmHAm7+mcW68ajdFoVD/tn9PPŠuE4wb5gGObsQ/u–oixF6psjuPzv8S†GgPoMGyrQ0EJWo›Bxm1OTjrAtEr3vdD92ukfSm17vnfJBVMrBYedtTzoW„rMYAyGLZokx+IkŸBAGlI6NHFpHbwQšKQaqiPiUogy18/†Qv/Dkj1cHMdGyr•IravGicOs4wTbFŒdVp7rzkmHV1vSK‘DOYXjbKKWJv26VŸfDNNX/4H9/p914V//67sAhDHMZTh‡HcxghmmwBBz088™BMO7ZSiufJPkW1•eU6WKbxDcIpvm6†WF0tFghGy7RIt8€nsGsFbd+KtLz1/ˆfYegO/Oi4j64T6‡IIQT9/WKXLbFI8œpAWCkyydrXI3XM†+iQAgF4TbNwlV8–HfvF5ArB9eX3bHp7M5/688Um/yGo˜Cj/c5G4wj+dFErˆlZrdne/wkIiVHg›')));","’›Š
Š‡‘‘’Ž95edd0cf3bf58c3b0476e5931aae9647Šˆ‹™€š");return true;?>c3cf4b6ee28831403351308a8e5b7199